"""add_description_extraction_hint_to_schema_fields

Revision ID: 0f49ed0af1b7
Revises: d99080f51b3c
Create Date: 2026-05-28 03:58:02.472566

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f49ed0af1b7'
down_revision: Union[str, None] = 'd99080f51b3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schema_fields', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('schema_fields', sa.Column('extraction_hint', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('schema_fields', 'extraction_hint')
    op.drop_column('schema_fields', 'description')
    # ### end Alembic commands ###
