"""add_status_source_to_data_instances

Revision ID: 4707b71da475
Revises: 95f0946f656b
Create Date: 2026-05-28 01:24:49.633099

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4707b71da475'
down_revision: Union[str, None] = '95f0946f656b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data_instances', sa.Column('status', sa.String(length=50), nullable=False))
    op.add_column('data_instances', sa.Column('source', sa.String(length=50), nullable=False))
    op.drop_index(op.f('ix_data_records_schema_id'), table_name='data_instances')
    op.create_index(op.f('ix_data_instances_schema_id'), 'data_instances', ['schema_id'], unique=False)
    op.drop_index(op.f('ix_field_values_data_record_id'), table_name='field_values')
    op.create_index(op.f('ix_field_values_data_instance_id'), 'field_values', ['data_instance_id'], unique=False)
    op.drop_index(op.f('ix_generated_documents_data_record_id'), table_name='generated_documents')
    op.create_index(op.f('ix_generated_documents_data_instance_id'), 'generated_documents', ['data_instance_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_generated_documents_data_instance_id'), table_name='generated_documents')
    op.create_index(op.f('ix_generated_documents_data_record_id'), 'generated_documents', ['data_instance_id'], unique=False)
    op.drop_index(op.f('ix_field_values_data_instance_id'), table_name='field_values')
    op.create_index(op.f('ix_field_values_data_record_id'), 'field_values', ['data_instance_id'], unique=False)
    op.drop_index(op.f('ix_data_instances_schema_id'), table_name='data_instances')
    op.create_index(op.f('ix_data_records_schema_id'), 'data_instances', ['schema_id'], unique=False)
    op.drop_column('data_instances', 'source')
    op.drop_column('data_instances', 'status')
    # ### end Alembic commands ###
