"""add password_hash to users

Revision ID: 6a346c1caa3a
Revises: 0f49ed0af1b7
Create Date: 2026-05-30 14:16:57.072802

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a346c1caa3a'
down_revision: Union[str, None] = '0f49ed0af1b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Delete all user-owned data before adding NOT NULL column (no legacy passwords exist)
    op.execute("DELETE FROM generated_documents")
    op.execute("DELETE FROM field_values")
    op.execute("DELETE FROM data_instances")
    op.execute("DELETE FROM token_mappings")
    op.execute("DELETE FROM templates")
    op.execute("DELETE FROM schema_fields")
    op.execute("DELETE FROM schemas")
    op.execute("DELETE FROM users")
    op.add_column('users', sa.Column('password_hash', sa.String(length=255), nullable=False))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password_hash')
    # ### end Alembic commands ###
