"""add_is_default_to_templates

Revision ID: d99080f51b3c
Revises: f9b97760e1bb
Create Date: 2026-05-28 02:00:27.324671

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd99080f51b3c'
down_revision: Union[str, None] = 'f9b97760e1bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('templates', sa.Column('is_default', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.alter_column('templates', 'is_default', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('templates', 'is_default')
    # ### end Alembic commands ###
