"""add_validation_fields_to_data_instances

Revision ID: f9b97760e1bb
Revises: 4707b71da475
Create Date: 2026-05-28 01:41:45.587288

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9b97760e1bb'
down_revision: Union[str, None] = '4707b71da475'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data_instances', sa.Column('validated_by', sa.UUID(), nullable=True))
    op.add_column('data_instances', sa.Column('validated_at', sa.DateTime(timezone=True), nullable=True))
    op.create_foreign_key(None, 'data_instances', 'users', ['validated_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'data_instances', type_='foreignkey')
    op.drop_column('data_instances', 'validated_at')
    op.drop_column('data_instances', 'validated_by')
    # ### end Alembic commands ###
